// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QSjeIAX5JFcZVlBUEf2z5dsYB05u8XI',
    appId: '1:592048758547:web:6d4b0e9c6be90cd45904e6',
    messagingSenderId: '592048758547',
    projectId: 'the-wall-bb488',
    authDomain: 'the-wall-bb488.firebaseapp.com',
    storageBucket: 'the-wall-bb488.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zGefN4WsSGN-7QAPKu4oTa62zMyaqrk',
    appId: '1:592048758547:android:f26346419d40e9d65904e6',
    messagingSenderId: '592048758547',
    projectId: 'the-wall-bb488',
    storageBucket: 'the-wall-bb488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXZ6Xv1uCk2iRWZmAJMqBe-Uzg2VCAEo',
    appId: '1:592048758547:ios:ad4dece93dc937165904e6',
    messagingSenderId: '592048758547',
    projectId: 'the-wall-bb488',
    storageBucket: 'the-wall-bb488.appspot.com',
    iosBundleId: 'com.example.socialMedialApp',
  );
}
